config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/quemsomos'
  get 'home/faleconosco'
  get 'home/sistemasweb'
  get 'home/cftv'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_header.html.erb
<nav class="navbar navbar-navbar navbar-static-top bs-docs-nav" id="top" role="banner">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <a class="navbar-brand" href="#">
        <%= image_tag 'logo-miranda-3.png' %>
      </a>
      <ul class="nav nav-pills navbar-right">

        <li role="presentation"><%= link_to "Home", home_index_path%></li>
        <li role="presentation"><%= link_to "Quem somos", home_quemsomos_path%></li>
        <li role="presentation"><%= link_to "Fale Conosco", home_faleconosco_path%></li>

        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            Sites <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <h5>Inícial<h5>
            <h5>E-commerce<h5>
            <h5>Portfolio<h5>
          </ul>
        </li>

        <li role="presentation"><%= link_to "Sistemas de Web", home_sistemasweb_path%></li>
        <li role="presentation"><%= link_to "CFTV", home_cftv_path%></li>

      </ul>
      <form class="navbar-form navbar-right">
        <div class="mini-icons">
          <a href="http://www.fb.com/"><%= image_tag "facebook.png"%><span class="hide">facebook</span></i></a>
        <a href="http://www.twitter.com/"><%= image_tag 'twitter.png' %><span class="hide">twitter</span></i></a>
      <a href="https://plus.google.com/"><%= image_tag "google.png"%><span class="hide">googlepl</span></i></a>
    <a href="http://www.instagram.com/"><%= image_tag "instagram.png"%><span class="hide">instagram</span></i></a>
  <a href="http://www.youtube.com/"><%= image_tag "youtube.png"%><span class="hide">youtube</span></i></a></div>
          </div>
        </form>
      </div>
    </div>
  </nav>

app/views/application/_rodape.html.erb
  <nav class="navbar navbar-navbar navbar-static-top bs-docs-nav" id="top" role="panel">
    <div class="container">
      <div class="panel-body">
        <p class="navbar-text navbar-left">Signed in as <a href="#" class="navbar-link">Miranda Web</a></p>

         <form class="navbar-form navbar-left">
        <div class="mini-icons">
          <a href="http://www.fb.com/" target="_blank"><%= image_tag "facebook.png"%><span class="hide">facebook</span></i></a>
        <a href="http://www.twitter.com/" target="_blank"><%= image_tag 'twitter.png' %><span class="hide">twitter</span></i></a>
      <a href="https://plus.google.com/" target="_blank"><%= image_tag "google.png"%><span class="hide">googlepl</span></i></a>
    <a href="http://www.instagram.com/" target="_blank"><%= image_tag "instagram.png"%><span class="hide">instagram</span></i></a>
  <a href="http://www.youtube.com/" target="_blank"><%= image_tag "youtube.png"%><span class="hide">youtube</span></i></a></div>
          </div>
        </form>

<ul class="breadcrumb navbar-right">
  <li><a href="#">A Empresa</a></li>
  <li><a href="#">Suporte Técnico</a></li>
  <li><a href="#">Solicite Seu Orçamento </a></li>
  <li class="active">Teremos a satisfação em atender !!!</li>
</ul>
</div>

      <div class="panel-footer">
        | Belém - Pará - Brasil
        | Contatos: (91) 3226-1601 - 98938-0498 - 98817-2825 |
         E-mail: fmirandaweb@gmail.com |
        </br>
        </br>
         Copyright © 2015 - Miranda Web
    </div>
  </div>
</nav>

app/views/home/cftv.html.erb
</br>
</br>
</br>

<div class="container">
<div class="jumbotron">
  <h2>Segurança Eletrônica</h2>
  <p>...</p>

</br>
</br>
</br>
</br>
</br>
</br>
</div>
</div>

</br>
</br>
</br>
</br>
</br>
</br>

app/views/home/faleconosco.html.erb
</br>
</br>
</br>

<div class="container">
<div class="jumbotron">
  <h2>Fale Conosco</h2>
  <p>...</p>

</br>
</br>
</br>
</br>
</br>
</br>
</div>
</div>

</br>
</br>
</br>
</br>
</br>
</br>

app/views/home/index.html.erb
</br>
</br>
</br>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag 'banner-principal.png' %>
      <div class="carousel-caption">
  <h3>QUER VENDER MAIS ???</h3>
    <p>Faça já sua loja virtual</p>

      </div>
    </div>
    <div class="item">
      <%= image_tag 'fundo responsivel.png' %>
      <div class="carousel-caption">
  <h3>SITES RESPONSIVOS !!!</h3>
    <p>Seu projeto compativel com qualquer tecnologia</p>

      </div>
    </div>
    <div class="item">
      <%= image_tag 'banner013.png' %>
      <div class="carousel-caption">
  <h3>PROJETOS INOVADORES !!!</h3>
    <p>Ideias novas</p>

      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
  </div>
  </div>
  </br>
  </br>
  </br>
  </br>
  </br>

app/views/home/quemsomos.html.erb
</br>
</br>
</br>

<div class="container">
<div class="jumbotron">
  <h2>Quem Somos</h2>
  </br>
  <p>In order to provide the best possible experience to old and buggy browsers, Bootstrap uses CSS browser hacks in several places to target special CSS to certain browser versions in order to work around bugs in the browsers themselves. These hacks understandably cause CSS validators to complain that they are invalid. In a couple places, we also use bleeding-edge CSS features that aren't yet fully standardized, but these are used purely for progressive enhancement.

     These validation warnings don't matter in practice since the non-hacky portion of our CSS does fully validate and the hacky portions don't interfere with the proper functioning of the non-hacky portion, hence why we deliberately ignore these particular warnings.

     Our HTML docs likewise have some trivial and inconsequential HTML validation warnings due to our inclusion of a workaround for a certain Firefox bug.</p>

</br>
</br>
</br>
</br>
</br>
</br>
</div>
</div>

</br>
</br>
</br>
</br>
</br>
</br>

app/views/home/sistemasweb.html.erb
</br>
</br>
</br>

<div class="container">
<div class="jumbotron">
  <h2>Sistemas de Web</h2>
  <p>...</p>

</br>
</br>
</br>
</br>
</br>
</br>
</div>
</div>

</br>
</br>
</br>
</br>
</br>
</br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mirandaweb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'header' %>

<%= yield %>

<%= render 'rodape' %>

</body>
</html>